### ISSUE TITLE
[Molecule] Failed to find required executable "npm" in paths:

### ISSUE THREAD

**Issue by dzintars** [oswee/ansible#56]
Running this task
```yaml
- name: Install Yarn NPM package globally
  community.general.npm:
    name: yarn@latest
    global: true
```
Molecule fails with:
```bash
TASK [yarn : Install Yarn NPM package globally] ********************************
fatal: [f34-yarn]: FAILED! => {
    "changed": false
}
MSG:
Failed to find required executable "npm" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin
```
But if i `molecule login -s vagrant` and `npm -v` i just get npm version back, so npm definitely is installed.

**Comment by dzintars** [comment]
One solution is quite hacky:
```yaml
- name: Install Yarn NPM package globally
  community.general.npm:
    name: yarn@latest
    global: true
  environment:
    PATH: /opt/nodejs/bin:{{ ansible_facts.env.PATH }}
```
This means i have "magic" variable `/opt/nodejs/bin` there.
The core of the issue is that i don't know how to set permissions for `/opt/nodejs` correctly. I set group ownership for `wheel` group.
The simplest way would be just install Node into `/usr/bin` or even `~/.local/opt`, but as far as i understand Filesystem Hierarchy Standard where `/opt` is for "Add-on application software packages." and NodeJS is right that...
